version: '3.8'
services:
  front:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file: .env
    image: ${PROJECT_NAME}:1.0.2
    container_name: ${PROJECT_NAME}
    restart: unless-stopped
    user: "1000:1000"
    expose:
      - $PORT
    ports:
      - 3000:4321